# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'Cover Charges' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
post_install do |installer|
  installer.pods_project.targets.each do |target|
    if ['SideMenu'].include? target.name
      target.build_configurations.each do |config|
        config.build_settings['SWIFT_VERSION'] = '4.2'
      end
    end
  end
end
  # Pods for Cover Charges

pod 'FacebookCore'
pod 'FacebookLogin'
pod 'FacebookShare'
pod 'Firebase/Core'
pod 'Firebase/Auth'
pod 'Stripe'
pod 'Firebase/Database'
pod 'ChameleonFramework/Swift', :git => 'https://github.com/ViccAlexander/Chameleon.git'
pod 'DropDown'
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!
pod 'SideMenu'



end
